Importo librerias para trabajar con json y dataframes de Pandas

In [1]:
import json
import pandas as pd

Leeo el archivo Json de cars.json creado en la notebook 1_Scrapping_Data.ipynb, y visualizo un pequeno set de datos. Para analizar los datos obtenidos

In [2]:
df = pd.read_json("1_cars.json", orient="columns")
df.tail()

,anchoVehiculo,capacidadAsientos,capacidadCarga,categoria,cilindrada,co2,codigoInformeTecnico,combustible,consumos,detalle,...,rendimientoUrbano,sistemaDistribucion,tipoMotor,tipoVehiculo,tipoVehiculoLey,traccion,transmision,valorMedidoNox,vigente,yearVehiculo
2845,NaN,NaN,NaN,CC3O,2.4,267,ZN5925E50814S02-7,Gasolina,0,"Rich 2,4 Lts. SOHC Camioneta Doble Cabina 4P. ...",...,7.1,NaN,NaN,Camioneta,NaN,4x2,M,NaN,True,0
2846,NaN,NaN,NaN,CC3O,2.4,267,ZN5925E50814S00-K,Gasolina,0,"Rich 2,4 Lts. SOHC Camioneta Doble Cabina 4P. ...",...,7.1,NaN,NaN,Camioneta,NaN,4x4,M,NaN,True,0
2847,NaN,NaN,NaN,CC3O,2.4,267,ZN5925E50814S01-3,Gasolina,0,"Rich Multipurpose 2,4 Lts. SOHC Camioneta Dobl...",...,7.1,NaN,NaN,Camioneta,NaN,4x4,M,NaN,True,0
2848,NaN,NaN,NaN,CC3O,2.4,267,ZN5925E50814S03-0,Gasolina,0,"Rich Multipurpose 2,4 Lts. SOHC Camioneta Dobl...",...,7.1,NaN,NaN,Camioneta,NaN,4x2,M,NaN,True,0
2849,NaN,NaN,NaN,LPO,1.3,158,ZT5966E51014S00-0,Gasolina,0,"Hunter (T200) 1,3 Lts. DOHC Station Wagon 5P. ...",...,12.6,NaN,NaN,Station Wagon,NaN,4x2,M,NaN,True,0

Cuantos modelos de autos tengo en el set de datos? Que campos no tienen datos?

In [3]:
print("Existen "+ len(df).__str__()+ " modelos")
print("Cantidad de registros que tienen datos nulos por cada campo")
print(df.isna().sum())

Existen 2850 modelos
Cantidad de registros que tienen datos nulos por cada campo
anchoVehiculo                      2850
capacidadAsientos                  2850
capacidadCarga                     2850
categoria                             0
cilindrada                            0
co2                                   0
codigoInformeTecnico                  0
combustible                           0
consumos                              0
detalle                               0
distanciaEntreEjes                 2850
eficienciaEnergetica               2850
empresaHomologa                       0
estado                             2850
fechaHomologacion                     0
fechaModificacion                  2850
idEtiqueta                            0
idMarca                               0
idModelo                              0
idVehiculo                            0
nombreEtiqueta                        0
nombreMarca                           0
nombreModelo                          0
norma                                 0
numeroPuertas                      2850
pesoBrutoVehicular                 2850
propulsion                            0
rendimientoCarretera                  0
rendimientoElectrico               2850
rendimientoMixto                      0
rendimientoPonderadoCombustible    2850
rendimientoPonderadoElectrico      2850
rendimientoUrbano                     0
sistemaDistribucion                2850
tipoMotor                          2850
tipoVehiculo                          0
tipoVehiculoLey                    2850
traccion                              0
transmision                           0
valorMedidoNox                     2850
vigente                               0
yearVehiculo                          0
dtype: int64

Elimino los datos en null porque no me intersan

In [4]:
df2 =df.dropna(axis=1, how='all')

In [5]:
df2.tail()

,categoria,cilindrada,co2,codigoInformeTecnico,combustible,consumos,detalle,empresaHomologa,fechaHomologacion,idEtiqueta,...,norma,propulsion,rendimientoCarretera,rendimientoMixto,rendimientoUrbano,tipoVehiculo,traccion,transmision,vigente,yearVehiculo
2845,CC3O,2.4,267,ZN5925E50814S02-7,Gasolina,0,"Rich 2,4 Lts. SOHC Camioneta Doble Cabina 4P. ...",Cidef Comercial S.A.,1417489200000,COMBUSTION GASOLINA,...,EURO V,CombustiÃ³n,10.4,8.9,7.1,Camioneta,4x2,M,True,0
2846,CC3O,2.4,267,ZN5925E50814S00-K,Gasolina,0,"Rich 2,4 Lts. SOHC Camioneta Doble Cabina 4P. ...",Cidef Comercial S.A.,1417489200000,COMBUSTION GASOLINA,...,EURO V,CombustiÃ³n,10.4,8.9,7.1,Camioneta,4x4,M,True,0
2847,CC3O,2.4,267,ZN5925E50814S01-3,Gasolina,0,"Rich Multipurpose 2,4 Lts. SOHC Camioneta Dobl...",Cidef Comercial S.A.,1417489200000,COMBUSTION GASOLINA,...,EURO V,CombustiÃ³n,10.4,8.9,7.1,Camioneta,4x4,M,True,0
2848,CC3O,2.4,267,ZN5925E50814S03-0,Gasolina,0,"Rich Multipurpose 2,4 Lts. SOHC Camioneta Dobl...",Cidef Comercial S.A.,1417489200000,COMBUSTION GASOLINA,...,EURO V,CombustiÃ³n,10.4,8.9,7.1,Camioneta,4x2,M,True,0
2849,LPO,1.3,158,ZT5966E51014S00-0,Gasolina,0,"Hunter (T200) 1,3 Lts. DOHC Station Wagon 5P. ...",Automotores Gildemeister S.p.A.,1421031600000,COMBUSTION GASOLINA,...,EURO V,CombustiÃ³n,17.1,15.1,12.6,Station Wagon,4x2,M,True,0

Miro la lisa de columnas disponibles, para ver el resultado final sin columnas en null

In [6]:
list(df2.columns)

['categoria',
 'cilindrada',
 'co2',
 'codigoInformeTecnico',
 'combustible',
 'consumos',
 'detalle',
 'empresaHomologa',
 'fechaHomologacion',
 'idEtiqueta',
 'idMarca',
 'idModelo',
 'idVehiculo',
 'nombreEtiqueta',
 'nombreMarca',
 'nombreModelo',
 'norma',
 'propulsion',
 'rendimientoCarretera',
 'rendimientoMixto',
 'rendimientoUrbano',
 'tipoVehiculo',
 'traccion',
 'transmision',
 'vigente',
 'yearVehiculo']

Comienzo a eliminar los columnas que no son datos relevantes para el modelo , y no incidiran en las predicciones finales.

In [7]:
#id de informte tecnico interno no sirve
df2.pop('codigoInformeTecnico')
#Tipo de combustible tampoco, solo tenemos autos de gasolina
df2.pop('combustible')
#Consumos lo tenemos con valor 0 en todas la filas, lo eliminamos
#df.consumos.unique()
df2.pop('consumos')
#eliminamos detalles , es un texto no especifico
df2.pop('detalle')
#fecha hologacion no nos sirve
df2.pop('fechaHomologacion')
df2.pop('idEtiqueta')
df2.pop('idMarca')
df2.pop('idModelo')
df2.pop('idVehiculo')
df2.pop('nombreEtiqueta')
df2.pop('nombreMarca')
df2.pop('nombreModelo')
#Propulsion todos las filas tiene combustible como valor, no sirve
#df.propulsion.unique()
df2.pop('propulsion')
#Elimino campo vigente interno
#df.vigente.unique()
df2.pop('vigente')
#Elimino year vehicule, todos los datos estan en 0 (cero)
#df.yearVehiculo.unique()
df2.pop('yearVehiculo')
df2.pop('empresaHomologa')

#SE ELIMINARA CATEGORIA PORQUE A LA FECHA NO SE INTERPRETO LO QUE SIGNIFICA.
df2.pop('categoria')


#Se eliminan datos que son importantes pero que en la prediccion son muy dificiles que se consigan para poderpredecir

df2.pop('co2')
df2.pop('rendimientoCarretera')
df2.pop('rendimientoUrbano')

0       12.2
1       16.4
2       16.1
3       16.4
4       10.7
5       16.1
6       16.1
7       10.7
8       10.7
9       13.0
10      13.0
11      13.0
12      13.0
13      10.3
14      10.3
15      16.7
16      16.9
17      13.2
18      13.2
19      13.2
20      13.2
21      16.4
22      16.9
23      16.4
24      15.9
25      15.9
26      14.7
27      15.9
28      14.7
29      16.7
        ...
2820    10.4
2821    10.8
2822     9.8
2823     8.6
2824     8.6
2825     9.6
2826     9.8
2827     9.4
2828     9.3
2829     9.7
2830     8.6
2831     8.8
2832     6.6
2833     7.1
2834     6.6
2835    10.4
2836    10.4
2837    10.2
2838     7.1
2839     7.1
2840     7.1
2841     7.1
2842    11.0
2843    11.0
2844    11.0
2845     7.1
2846     7.1
2847     7.1
2848     7.1
2849    12.6
Name: rendimientoUrbano, Length: 2850, dtype: float64

In [8]:
df2.tail()

      cilindrada   norma  rendimientoMixto   tipoVehiculo traccion transmision
2845         2.4  EURO V               8.9      Camioneta      4x2           M
2846         2.4  EURO V               8.9      Camioneta      4x4           M
2847         2.4  EURO V               8.9      Camioneta      4x4           M
2848         2.4  EURO V               8.9      Camioneta      4x2           M
2849         1.3  EURO V              15.1  Station Wagon      4x2           M

In [9]:
list(df2.columns)

['cilindrada',
 'norma',
 'rendimientoMixto',
 'tipoVehiculo',
 'traccion',
 'transmision']

Comienzo a categorizar las columnas en este estado, reviso el primer campo a categorizar

In [10]:
df2.norma.unique()

array(['EURO V', 'EURO VI', 'TIER 3 B50', 'TIER 2 B5', 'TIER 2 B4',
       'TIER 3 B70', 'TIER 2 B6', 'TIER 2 B8', 'TIER 2 B7', 'Tier 3 B125',
       'TIER 3 B125', 'TIER 3 B30'], dtype=object)

In [11]:
norma= df2.pop('norma')
#norma
df2['EURO V'] = (norma == 'EURO V')*1.0
df2['EURO VI'] = (norma == 'EURO VI')*1.0
df2['TIER 3 B50'] = (norma == 'TIER 3 B50')*1.0
df2['TIER 2 B5'] = (norma == 'TIER 2 B5')*1.0
df2['TIER 2 B4'] = (norma == 'TIER 2 B4')*1.0
df2['TIER 3 B70'] = (norma == 'TIER 3 B70')*1.0
df2['TIER 2 B6'] = (norma == 'TIER 2 B6')*1.0
df2['TIER 2 B8'] = (norma == 'TIER 2 B8')*1.0
df2['TIER 2 B7'] = (norma == 'TIER 2 B7')*1.0
df2['Tier 3 B125'] = (norma == 'Tier 3 B125')*1.0
df2['TIER 3 B125'] = (norma == 'TIER 3 B125')*1.0
df2['TIER 3 B30'] = (norma == 'TIER 3 B30')*1.0

df2.tail()

/Users/alvaroteixeira/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/alvaroteixeira/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/Users/alvaroteixeira/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
/Users/alvaroteixeira/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/alvaroteixeira/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
/Users/alvaroteixeira/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/alvaroteixeira/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/Users/alvaroteixeira/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
/Users/alvaroteixeira/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
/Users/alvaroteixeira/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':
/Users/alvaroteixeira/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
/Users/alvaroteixeira/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,cilindrada,rendimientoMixto,tipoVehiculo,traccion,transmision,EURO V,EURO VI,TIER 3 B50,TIER 2 B5,TIER 2 B4,TIER 3 B70,TIER 2 B6,TIER 2 B8,TIER 2 B7,Tier 3 B125,TIER 3 B125,TIER 3 B30
2845,2.4,8.9,Camioneta,4x2,M,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2846,2.4,8.9,Camioneta,4x4,M,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2847,2.4,8.9,Camioneta,4x4,M,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2848,2.4,8.9,Camioneta,4x2,M,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2849,1.3,15.1,Station Wagon,4x2,M,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
df2.tipoVehiculo.unique()

array(['Hatch Back', 'SedÃ¡n', 'Station Wagon', 'Cabriolet', 'CoupÃ©',
       'Convertible', 'FurgÃ³n', 'Jeep', 'Limusina', 'Roadster',
       'Camioneta', 'Minivan', 'FurgÃ³n Cerrado', 'Minibus', 'Microvan'],
      dtype=object)

In [13]:
tipoVehiculo= df2.pop('tipoVehiculo')
#tipoVehiculo
df2['Hatch Back'] = (tipoVehiculo == 'Hatch Back')*1.0
df2['SedÃ¡n'] = (tipoVehiculo == 'SedÃ¡n')*1.0
df2['Station Wagon'] = (tipoVehiculo == 'Station Wagon')*1.0
df2['Cabriolet'] = (tipoVehiculo == 'Cabriolet')*1.0
df2['CoupÃ©'] = (tipoVehiculo == 'CoupÃ©')*1.0
df2['Convertible'] = (tipoVehiculo == 'Convertible')*1.0
df2['FurgÃ³n'] = (tipoVehiculo == 'FurgÃ³n')*1.0
df2['Jeep'] = (tipoVehiculo == 'Jeep')*1.0
df2['Limusina'] = (tipoVehiculo == 'Limusina')*1.0
df2['Roadster'] = (tipoVehiculo == 'Roadster')*1.0
df2['Camioneta'] = (tipoVehiculo == 'Camioneta')*1.0
df2['Minivan'] = (tipoVehiculo == 'Minivan')*1.0
df2['FurgÃ³n Cerrado'] = (tipoVehiculo == 'FurgÃ³n Cerrado')*1.0
df2['Minibus'] = (tipoVehiculo == 'Minibus')*1.0
df2['Microvan'] = (tipoVehiculo == 'Microvan')*1.0
df2.tail()

/Users/alvaroteixeira/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/alvaroteixeira/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/Users/alvaroteixeira/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
/Users/alvaroteixeira/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/alvaroteixeira/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
/Users/alvaroteixeira/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/alvaroteixeira/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/Users/alvaroteixeira/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
/Users/alvaroteixeira/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
/Users/alvaroteixeira/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':
/Users/alvaroteixeira/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
/Users/alvaroteixeira/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/alvaroteixeira/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/Users/alvaroteixeira/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/Users/alvaroteixeira/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,cilindrada,rendimientoMixto,traccion,transmision,EURO V,EURO VI,TIER 3 B50,TIER 2 B5,TIER 2 B4,TIER 3 B70,...,Convertible,FurgÃ³n,Jeep,Limusina,Roadster,Camioneta,Minivan,FurgÃ³n Cerrado,Minibus,Microvan
2845,2.4,8.9,4x2,M,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2846,2.4,8.9,4x4,M,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2847,2.4,8.9,4x4,M,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2848,2.4,8.9,4x2,M,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2849,1.3,15.1,4x2,M,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
df2.traccion.unique()

array(['4x2', '4x4'], dtype=object)

In [15]:
traccion= df2.pop('traccion')
#traccion
df2['4x2'] = (traccion == '4x2')*1.0
df2['4x4'] = (traccion == '4x4')*1.0
df2.tail()

/Users/alvaroteixeira/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/alvaroteixeira/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

,cilindrada,rendimientoMixto,transmision,EURO V,EURO VI,TIER 3 B50,TIER 2 B5,TIER 2 B4,TIER 3 B70,TIER 2 B6,...,Jeep,Limusina,Roadster,Camioneta,Minivan,FurgÃ³n Cerrado,Minibus,Microvan,4x2,4x4
2845,2.4,8.9,M,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2846,2.4,8.9,M,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
2847,2.4,8.9,M,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
2848,2.4,8.9,M,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2849,1.3,15.1,M,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [16]:
df2.transmision.unique()

array(['M', 'A'], dtype=object)

In [17]:
transmision= df2.pop('transmision')
#traccion
df2['M'] = (transmision == 'M')*1.0
df2['A'] = (transmision == 'A')*1.0
df2.tail()

/Users/alvaroteixeira/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/alvaroteixeira/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

,cilindrada,rendimientoMixto,EURO V,EURO VI,TIER 3 B50,TIER 2 B5,TIER 2 B4,TIER 3 B70,TIER 2 B6,TIER 2 B8,...,Roadster,Camioneta,Minivan,FurgÃ³n Cerrado,Minibus,Microvan,4x2,4x4,M,A
2845,2.4,8.9,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2846,2.4,8.9,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
2847,2.4,8.9,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
2848,2.4,8.9,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2849,1.3,15.1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

Guardo el resultado en un json

In [18]:
print ("Save file cars_to_model_proces.json..")

df2.to_json('2_cars_to_model_proces.json')

Save file cars_to_model_proces.json..